In [5]:
import pandas as pd
import numpy as np
import os
import tarfile
import requests
import json

In [3]:

file_path = '/Users/mukulkothari/Work/MPE/Datasets/MusicBrainz/JSON/area.tar.xz'
op_file_path = '/Users/mukulkothari/Work/MPE/Datasets/MusicBrainz/JSON/area_raw/'

# Open your tar file
with tarfile.open(file_path, 'r') as tar:
    # List all members
    for member in tar.getmembers():
        print(member.name)
        # Extract each member
        tar.extract(member, path=op_file_path)

TIMESTAMP
COPYING
README
REPLICATION_SEQUENCE
SCHEMA_SEQUENCE
mbdump/area
JSON_DUMPS_SCHEMA_NUMBER

In [4]:
def data_explorer(json_file_path):
    df = pd.read_json(json_file_path, lines=True)
    # df.head()
    print (df.columns)
    print(df.shape)
    return df

In [18]:
json_file_path = '/Users/mukulkothari/Work/MPE/Datasets/MusicBrainz/JSON/area/mbdump/area'
# json_file_path = '/Users/mukulkothari/Work/MPE/Datasets/MusicBrainz/JSON/artist/mbdump/artist'
df = data_explorer(json_file_path)
df.head()

Index(['disambiguation', 'aliases', 'type', 'id', 'name', 'sort-name',
       'life-span', 'relations', 'tags', 'genres', 'type-id', 'annotation',
       'iso-3166-2-codes', 'iso-3166-1-codes', 'iso-3166-3-codes'],
      dtype='object')
(119111, 15)

,disambiguation,aliases,type,id,name,sort-name,life-span,relations,tags,genres,type-id,annotation,iso-3166-2-codes,iso-3166-1-codes,iso-3166-3-codes
0,,[],Municipality,7e943e62-1d68-4da2-bda4-5e6c9a57542f,San Severino Lucano,San Severino Lucano,"{'ended': False, 'begin': None, 'end': None}","[{'begin': None, 'end': None, 'attribute-ids':...",[],[],17246454-5ac4-36a1-b81a-4753eb2dab20,None,NaN,NaN,NaN
1,,"[{'ended': False, 'sort-name': 'Bagnacavallo',...",Municipality,132db20d-8426-461e-bcaf-9b5f597ad453,Bagnacavallo,Bagnacavallo,"{'ended': False, 'begin': None, 'end': None}","[{'target-type': 'area', 'attributes': [], 'at...",[],[],17246454-5ac4-36a1-b81a-4753eb2dab20,None,NaN,NaN,NaN
2,,[],Municipality,d3c7e754-c40b-4211-bfc2-32d975d86765,Andreis,Andreis,"{'begin': None, 'end': None, 'ended': False}","[{'end': None, 'begin': None, 'ended': False, ...",[],[],17246454-5ac4-36a1-b81a-4753eb2dab20,None,NaN,NaN,NaN
3,,[],Municipality,2f43bd50-bada-4c10-a2a5-2c585c046b0c,Savogna d'Isonzo,Savogna d'Isonzo,"{'ended': False, 'begin': None, 'end': None}",[{'type-id': 'de7cc874-8b1b-3a05-8272-f3834c96...,[],[],17246454-5ac4-36a1-b81a-4753eb2dab20,None,NaN,NaN,NaN
4,,[],Municipality,a16a6c34-ca60-4497-99b8-1bfc506d8621,Cimolais,Cimolais,"{'ended': False, 'begin': None, 'end': None}","[{'begin': None, 'end': None, 'ended': False, ...",[],[],17246454-5ac4-36a1-b81a-4753eb2dab20,None,NaN,NaN,NaN

In [25]:
tar_path = '/Users/mukulkothari/Work/MPE/Datasets/MusicBrainz/JSON/artist.tar.xz'
json_file_name = 'mbdump/artist'  # Name or path of the JSON file inside the TAR archive
extract_path  = '/Users/mukulkothari/Work/MPE/Datasets/MusicBrainz/JSON/artist'   # Directory where you want to extract the file

with tarfile.open(tar_path, 'r') as tar:
    tar.extract(json_file_name, path=extract_path)

In [ ]:
json_file_path = '/Users/mukulkothari/Work/MPE/Datasets/MusicBrainz/JSON/artist/mbdump/artist'
df = data_explorer(json_file_path)
df.head()

In [ ]:
####################################

## Using API

In [40]:
def get_musicbrainz_artist_data(artist_name):
    base_url = "https://musicbrainz.org/ws/2/"
    endpoint = "artist/"
    query_params = {
        "query": artist_name,
        "fmt": "json"
    }
    
    # Construct the full URL
    request_url = f"{base_url}{endpoint}"
    
    # Headers to mimic a browser request
    headers = {
        'User-Agent': 'AppName/1.0 ( YourContactInfo )',
        'Accept': 'application/json'
    }
    
    # Make the request
    response = requests.get(request_url, params=query_params, headers=headers)
    
    # Check if the request was successful
    if response.status_code == 200:
        # Parse the JSON response
        data = response.json()
        
        # Returning the full data for demonstration purposes
        # You might want to process this data further to fit your needs
        return data
    else:
        print("Failed to retrieve data")
        return None

# Example usage
artist_name = "Michael Jackson"
data = get_musicbrainz_artist_data(artist_name)

# Print the result
print(json.dumps(data, indent=4))

{
    "created": "2024-03-07T07:57:09.720Z",
    "count": 15091,
    "offset": 0,
    "artists": [
        {
            "id": "f27ec8db-af05-4f36-916e-3d57f91ecf5e",
            "type": "Person",
            "type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
            "score": 100,
            "gender-id": "36d3d30a-839d-3eda-8cb3-29be4384e4a9",
            "name": "Michael Jackson",
            "sort-name": "Jackson, Michael",
            "gender": "male",
            "country": "US",
            "area": {
                "id": "489ce91b-6658-3307-9877-795b68554c98",
                "type": "Country",
                "type-id": "06dd0ae4-8c74-30bb-b43d-95dcedf961de",
                "name": "United States",
                "sort-name": "United States",
                "life-span": {
                    "ended": null
                }
            },
            "begin-area": {
                "id": "34357067-8f7f-4c7a-8d5e-99b6e60f7891",
                "type": "City",
                "type-id": "6fd8f29a-3d0a-32fc-980d-ea697b69da78",
                "name": "Gary",
                "sort-name": "Gary",
                "life-span": {
                    "ended": null
                }
            },
            "end-area": {
                "id": "1f40c6e1-47ba-4e35-996f-fe6ee5840e62",
                "type": "City",
                "type-id": "6fd8f29a-3d0a-32fc-980d-ea697b69da78",
                "name": "Los Angeles",
                "sort-name": "Los Angeles",
                "life-span": {
                    "ended": null
                }
            },
            "disambiguation": "\u201cKing of Pop\u201d",
            "ipis": [
                "00002961801",
                "00523553664"
            ],
            "isnis": [
                "000000011023081X"
            ],
            "life-span": {
                "begin": "1958-08-29",
                "end": "2009-06-25",
                "ended": true
            },
            "aliases": [
                {
                    "sort-name": "\u8fc8\u514b\u5c14\u00b7\u6770\u514b\u900a",
                    "name": "\u8fc8\u514b\u5c14\u00b7\u6770\u514b\u900a",
                    "locale": "zh_Hans",
                    "type": null,
                    "primary": null,
                    "begin-date": null,
                    "end-date": null
                },
                {
                    "sort-name": "\u041c\u0430\u0439\u043a\u043b \u0414\u0436\u0435\u043a\u0441\u043e\u043d",
                    "name": "\u041c\u0430\u0439\u043a\u043b \u0414\u0436\u0435\u043a\u0441\u043e\u043d",
                    "locale": "ru",
                    "type": null,
                    "primary": null,
                    "begin-date": null,
                    "end-date": null
                },
                {
                    "sort-name": "\u30de\u30a4\u30b1\u30eb\u30fb\u30b8\u30e3\u30af\u30bd\u30f3",
                    "name": "\u30de\u30a4\u30b1\u30eb\u30fb\u30b8\u30e3\u30af\u30bd\u30f3",
                    "locale": "ja",
                    "type": null,
                    "primary": true,
                    "begin-date": null,
                    "end-date": null
                },
                {
                    "sort-name": "\ub9c8\uc774\ud074 \uc7ad\uc2a8",
                    "name": "\ub9c8\uc774\ud074 \uc7ad\uc2a8",
                    "locale": "ko",
                    "type": null,
                    "primary": true,
                    "begin-date": null,
                    "end-date": null
                },
                {
                    "sort-name": "Michel Jackson",
                    "name": "Michel Jackson",
                    "locale": null,
                    "type": null,
                    "primary": null,
                    "begin-date": null,
                    "end-date": null
                },
                {
                    "sort-name": "JACKSON MICHAEL JOE",
                    "name": "JACKSON MICHAEL JOE",
                    "locale": null,
                    "type": null,
                    "primary": null,
                    "begin-date": null,
                    "end-date": null
                },
                {
                    "sort-name": "Micha\u00ebl Jackson",
                    "name": "Micha\u00ebl Jackson",
                    "locale": null,
                    "type": null,
                    "primary": null,
                    "begin-date": null,
                    "end-date": null
                },
                {
                    "sort-name": "Jackson, Michael Joe",
                    "name": "Michael Joe Jackson",
                    "locale": null,
                    "type": null,
                    "primary": null,
                    "begin-date": null,
                    "end-date": null
                },
                {
                    "sort-name": "Micheal",
                    "type-id": "1937e404-b981-3cb7-8151-4c86ebfc8d8e",
                    "name": "Micheal",
                    "locale": null,
                    "type": "Search hint",
                    "primary": null,
                    "begin-date": null,
                    "end-date": null
                },
                {
                    "sort-name": "Jackson, Michael",
                    "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
                    "name": "Michael Jackson",
                    "locale": "en",
                    "type": "Artist name",
                    "primary": true,
                    "begin-date": null,
                    "end-date": null
                },
                {
                    "sort-name": "Jackson, Michael Joseph",
                    "type-id": "d4dcd0c0-b341-3612-a332-c0ce797b25cf",
                    "name": "Michael Joseph Jackson",
                    "locale": null,
                    "type": "Legal name",
                    "primary": null,
                    "begin-date": null,
                    "end-date": null
                }
            ],
            "tags": [
                {
                    "count": 1,
                    "name": "rock"
                },
                {
                    "count": 20,
                    "name": "pop"
                },
                {
                    "count": 2,
                    "name": "american"
                },
                {
                    "count": 1,
                    "name": "blues"
                },
                {
                    "count": 0,
                    "name": "singer"
                },
                {
                    "count": 0,
                    "name": "usa"
                },
                {
                    "count": 1,
                    "name": "funk"
                },
                {
                    "count": 6,
                    "name": "soul"
                },
                {
                    "count": 10,
                    "name": "disco"
                },
                {
                    "count": 0,
                    "name": "rnb"
                },
                {
                    "count": 0,
                    "name": "composer"
                },
                {
                    "count": 0,
                    "name": "am\u00e9ricain"
                },
                {
                    "count": 0,
                    "name": "lyricist"
                },
                {
                    "count": 12,
                    "name": "dance-pop"
                },
                {
                    "count": 1,
                    "name": "pop rock"
                },
                {
                    "count": 0,
                    "name": "rhythm and blues"
                },
                {
                    "count": 1,
                    "name": "new jack swing"
                },
                {
                    "count": 1,
                    "name": "folk pop"
                },
                {
                    "count": 0,
                    "name": "parolier"
                },
                {
                    "count": 0,
                    "name": "chanteur"
                },
                {
                    "count": 0,
                    "name": "compositeur"
                },
                {
                    "count": 1,
                    "name": "motown"
                },
                {
                    "count": 0,
                    "name": "classic pop and rock"
                },
                {
                    "count": 0,
                    "name": "cool"
                },
                {
                    "count": 0,
                    "name": "united states"
                },
                {
                    "count": 3,
                    "name": "pop soul"
                },
                {
                    "count": 0,
                    "name": "michael-jackson"
                },
                {
                    "count": 0,
                    "name": "contemporary rnb"
                },
                {
                    "count": 2,
                    "name": "post-disco"
                },
                {
                    "count": 3,
                    "name": "r&b"
                },
                {
                    "count": 7,
                    "name": "contemporary r&b"
                },
                {
                    "count": 2,
                    "name": "death by drug overdose"
                }
            ]
        },
        {
            "id": "8a92b6b3-1e91-45b5-8936-a0d6787a8be3",
            "score": 88,
            "name": "Michael Jackson",
            "sort-name": "Jackson, Michael",
            "disambiguation": "mashups",
            "life-span": {
                "ended": null
            }
        },
        {
            "id": "f1be8703-f308-425a-ac31-6fb304cfb60c",
            "type": "Person",
            "type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
            "score": 88,
            "gender-id": "36d3d30a-839d-3eda-8cb3-29be4384e4a9",
            "name": "Michael Jackson",
            "sort-name": "Jackson, Michael",
            "gender": "male",
            "country": "GB",
            "area": {
                "id": "8a754a16-0027-3a29-b6d7-2b40ea0481ed",
                "type": "Country",
                "type-id": "06dd0ae4-8c74-30bb-b43d-95dcedf961de",
                "name": "United Kingdom",
                "sort-name": "United Kingdom",
                "life-span": {
                    "ended": null
                }
            },
            "disambiguation": "vocals in English heavy metal band Pariah",
            "life-span": {
                "ended": null
            },
            "tags": [
                {
                    "count": 1,
                    "name": "invincible"
                }
            ]
        },
        {
            "id": "ce8f1c65-1c0e-4685-bea5-f7a27a20b3bf",
            "type": "Person",
            "type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
            "score": 88,
            "gender-id": "36d3d30a-839d-3eda-8cb3-29be4384e4a9",
            "name": "Michael Jackson",
            "sort-name": "Jackson, Michael",
            "gender": "male",
            "country": "AU",
            "area": {
                "id": "106e0bec-b638-3b37-b731-f53d507dc00e",
                "type": "Country",
                "type-id": "06dd0ae4-8c74-30bb-b43d-95dcedf961de",
                "name": "Australia",
                "sort-name": "Australia",
                "life-span": {
                    "ended": null
                }
            },
            "disambiguation": "Australian didgeridoo and didjeribone player",
            "life-span": {
                "ended": null
            }
        },
        {
            "id": "e05cfe05-7e81-430e-a27b-fb910f46f008",
            "score": 88,
            "name": "Michael Jackson",
            "sort-name": "Jackson, Michael",
            "disambiguation": "Neal Morse related vocalist",
            "life-span": {
                "ended": null
            }
        },
        {
            "id": "de05e891-e9ee-465c-ad70-6ace189b7cbb",
            "type": "Person",
            "type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
            "score": 88,
            "gender-id": "36d3d30a-839d-3eda-8cb3-29be4384e4a9",
            "name": "Michael Jackson",
            "sort-name": "Jackson, Michael",
            "gender": "male",
            "country": "NZ",
            "area": {
                "id": "8524c7d9-f472-3890-a458-f28d5081d9c4",
                "type": "Country",
                "type-id": "06dd0ae4-8c74-30bb-b43d-95dcedf961de",
                "name": "New Zealand",
                "sort-name": "New Zealand",
                "life-span": {
                    "ended": null
                }
            },
            "begin-area": {
                "id": "c6725380-3835-4f29-b795-3519258a00d4",
                "type": "City",
                "type-id": "6fd8f29a-3d0a-32fc-980d-ea697b69da78",
                "name": "Nelson City",
                "sort-name": "Nelson City",
                "life-span": {
                    "ended": null
                }
            },
            "disambiguation": "NZ poet & anthropologist",
            "isnis": [
                "0000000110273174"
            ],
            "life-span": {
                "begin": "1939",
                "ended": null
            },
            "aliases": [
                {
                    "sort-name": "Jackson, Michael D.",
                    "type-id": "d4dcd0c0-b341-3612-a332-c0ce797b25cf",
                    "name": "Michael D. Jackson",
                    "locale": "en",
                    "type": "Legal name",
                    "primary": null,
                    "begin-date": null,
                    "end-date": null
                }
            ]
        },
        {
            "id": "5fc89998-cf26-4ec0-8fff-1398e34e7b61",
            "type": "Person",
            "type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
            "score": 76,
            "gender-id": "36d3d30a-839d-3eda-8cb3-29be4384e4a9",
            "name": "George Michael Jackson",
            "sort-name": "Jackson, George Michael",
            "gender": "male",
            "life-span": {
                "ended": null
            }
        },
        {
            "id": "49c562af-aa65-4a0b-998b-58d9b7df447e",
            "score": 76,
            "name": "Michael Jackson's Doctor",
            "sort-name": "Michael Jackson's Doctor",
            "life-span": {
                "ended": null
            }
        },
        {
            "id": "c28f8611-9c71-4734-9f3c-2549fbd665bc",
            "type": "Person",
            "type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
            "score": 73,
            "gender-id": "36d3d30a-839d-3eda-8cb3-29be4384e4a9",
            "name": "Musa Keys",
            "sort-name": "Musa Keys",
            "gender": "male",
            "life-span": {
                "ended": null
            },
            "aliases": [
                {
                    "sort-name": "Tsonga Michael Jackson",
                    "name": "Tsonga Michael Jackson",
                    "locale": null,
                    "type": null,
                    "primary": null,
                    "begin-date": null,
                    "end-date": null
                }
            ]
        },
        {
            "id": "5857471e-4238-4cd4-8c2e-1d9108db79c9",
            "type": "Person",
            "type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
            "score": 70,
            "gender-id": "36d3d30a-839d-3eda-8cb3-29be4384e4a9",
            "name": "Prince Michael Jackson I",
            "sort-name": "Jackson, Prince Michael, I",
            "gender": "male",
            "country": "US",
            "area": {
                "id": "489ce91b-6658-3307-9877-795b68554c98",
                "type": "Country",
                "type-id": "06dd0ae4-8c74-30bb-b43d-95dcedf961de",
                "name": "United States",
                "sort-name": "United States",
                "life-span": {
                    "ended": null
                }
            },
            "begin-area": {
                "id": "1f40c6e1-47ba-4e35-996f-fe6ee5840e62",
                "type": "City",
                "type-id": "6fd8f29a-3d0a-32fc-980d-ea697b69da78",
                "name": "Los Angeles",
                "sort-name": "Los Angeles",
                "life-span": {
                    "ended": null
                }
            },
            "disambiguation": "eldest son of Michael Jackson",
            "life-span": {
                "begin": "1997-02-13",
                "ended": null
            },
            "aliases": [
                {
                    "sort-name": "Jackson, Michael Joseph, Jr.",
                    "type-id": "d4dcd0c0-b341-3612-a332-c0ce797b25cf",
                    "name": "Michael Joseph Jackson, Jr.",
                    "locale": null,
                    "type": "Legal name",
                    "primary": null,
                    "begin-date": null,
                    "end-date": null
                },
                {
                    "sort-name": "Prince Jackson",
                    "name": "Prince Jackson",
                    "locale": null,
                    "type": null,
                    "primary": null,
                    "begin-date": null,
                    "end-date": null
                }
            ],
            "tags": [
                {
                    "count": 1,
                    "name": "soul"
                }
            ]
        },
        {
            "id": "0af139d6-a56d-42c8-ab70-f27ceb9d5e92",
            "type": "Person",
            "type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
            "score": 62,
            "gender-id": "36d3d30a-839d-3eda-8cb3-29be4384e4a9",
            "name": "Christ'OF",
            "sort-name": "Christ'OF",
            "gender": "male",
            "country": "BE",
            "area": {
                "id": "5b8a5ee5-0bb3-34cf-9a75-c27c44e341fc",
                "type": "Country",
                "type-id": "06dd0ae4-8c74-30bb-b43d-95dcedf961de",
                "name": "Belgium",
                "sort-name": "Belgium",
                "life-span": {
                    "ended": null
                }
            },
            "disambiguation": "Belgian Michael Jackson impersonator",
            "life-span": {
                "begin": "1972-03-28",
                "ended": null
            },
            "aliases": [
                {
                    "sort-name": "Lequesne, Christophe",
                    "type-id": "d4dcd0c0-b341-3612-a332-c0ce797b25cf",
                    "name": "Christophe Lequesne",
                    "locale": null,
                    "type": "Legal name",
                    "primary": null,
                    "begin-date": null,
                    "end-date": null
                },
                {
                    "sort-name": "Michael Jackson Legacy",
                    "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
                    "name": "Michael Jackson Legacy",
                    "locale": null,
                    "type": "Artist name",
                    "primary": null,
                    "begin-date": null,
                    "end-date": null
                }
            ]
        },
        {
            "id": "9d1818d3-0d61-4e76-b6c5-5b4883f792fd",
            "type": "Person",
            "type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
            "score": 61,
            "gender-id": "93452b5a-a947-30c8-934f-6a4056b151c2",
            "name": "Paris Jackson",
            "sort-name": "Jackson, Paris",

In [39]:
def get_musicbrainz_genre_data(genre_name):
    base_url = "https://musicbrainz.org/ws/2/"
    endpoint = "genre/"
    query_params = {
        "query": genre_name,
        "fmt": "json"
    }
    
    # Construct the full URL
    request_url = f"{base_url}{endpoint}"
    
    # Headers to mimic a browser request
    headers = {
        'User-Agent': 'AppName/1.0 ( YourContactInfo )',
        'Accept': 'application/json'
    }
    
    # Make the request
    response = requests.get(request_url, params=query_params, headers=headers)
    
    # Check if the request was successful
    if response.status_code == 200:
        # Parse the JSON response
        data = response.json()
        
        # Returning the full data for demonstration purposes
        # You might want to process this data further to fit your needs
        return data
    else:
        print("Failed to retrieve data")
        return None

# Example usage
genre_name = "Rock"
data = get_musicbrainz_genre_data(genre_name)

# Print the result
print(json.dumps(data, indent=4))

Failed to retrieve data
null

In [38]:
if data and 'genre' in data:
    df = pd.DataFrame(data['genre'])
    print(df.head())
else:
    print("No data to load into DataFrame")

No data to load into DataFrame

In [41]:
if data and 'artists' in data:
    df = pd.DataFrame(data['artists'])
    print(df.head())
else:
    print("No data to load into DataFrame")

                                     id    type  \
0  f27ec8db-af05-4f36-916e-3d57f91ecf5e  Person
1  8a92b6b3-1e91-45b5-8936-a0d6787a8be3     NaN
2  f1be8703-f308-425a-ac31-6fb304cfb60c  Person
3  ce8f1c65-1c0e-4685-bea5-f7a27a20b3bf  Person
4  e05cfe05-7e81-430e-a27b-fb910f46f008     NaN

                                type-id  score  \
0  b6e035f4-3ce9-331c-97df-83397230b0df    100
1                                   NaN     88
2  b6e035f4-3ce9-331c-97df-83397230b0df     88
3  b6e035f4-3ce9-331c-97df-83397230b0df     88
4                                   NaN     88

                              gender-id             name         sort-name  \
0  36d3d30a-839d-3eda-8cb3-29be4384e4a9  Michael Jackson  Jackson, Michael
1                                   NaN  Michael Jackson  Jackson, Michael
2  36d3d30a-839d-3eda-8cb3-29be4384e4a9  Michael Jackson  Jackson, Michael
3  36d3d30a-839d-3eda-8cb3-29be4384e4a9  Michael Jackson  Jackson, Michael
4                                   NaN  Michael Jackson  Jackson, Michael

  gender country                                               area  \
0   male      US  {'id': '489ce91b-6658-3307-9877-795b68554c98',...
1    NaN     NaN                                                NaN
2   male      GB  {'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed',...
3   male      AU  {'id': '106e0bec-b638-3b37-b731-f53d507dc00e',...
4    NaN     NaN                                                NaN

                                          begin-area  \
0  {'id': '34357067-8f7f-4c7a-8d5e-99b6e60f7891',...
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                            end-area  \
0  {'id': '1f40c6e1-47ba-4e35-996f-fe6ee5840e62',...
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                 disambiguation                        ipis  \
0                                 “King of Pop”  [00002961801, 00523553664]
1                                       mashups                         NaN
2     vocals in English heavy metal band Pariah                         NaN
3  Australian didgeridoo and didjeribone player                         NaN
4                   Neal Morse related vocalist                         NaN

                isnis                                          life-span  \
0  [000000011023081X]  {'begin': '1958-08-29', 'end': '2009-06-25', '...
1                 NaN                                    {'ended': None}
2                 NaN                                    {'ended': None}
3                 NaN                                    {'ended': None}
4                 NaN                                    {'ended': None}

                                             aliases  \
0  [{'sort-name': '迈克尔·杰克逊', 'name': '迈克尔·杰克逊', '...
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                tags
0  [{'count': 1, 'name': 'rock'}, {'count': 20, '...
1                                                NaN
2               [{'count': 1, 'name': 'invincible'}]
3                                                NaN
4                                                NaN

In [17]:
from pandas import json_normalize

# Example for nested JSON data
if data and 'artists' in data:
    df = json_normalize(data['artists'])
    print(df.head())
else:
    print("No data to load into DataFrame")

                                     id    type  \
0  012151a8-0f9a-44c9-997f-ebd68b5389f9   Group
1  c477a6e5-a76d-48db-943c-cfe230de9a16  Person
2  ed98e598-5ab1-4d38-923c-449e8dc89bf5  Person
3  a7dac21e-c4d1-4857-9eb4-91ebb2d06c94   Group
4  3db8a0bf-3e9a-43e4-8afc-53479f05685b  Person

                                type-id  score             name  \
0  e431f5f6-b5d2-343d-8b36-72607fffb74b    100  Imagine Dragons
1  b6e035f4-3ce9-331c-97df-83397230b0df     43        Ben McKee
2  b6e035f4-3ce9-331c-97df-83397230b0df     43      Andrew Beck
3  e431f5f6-b5d2-343d-8b36-72607fffb74b     36          Imagine
4  b6e035f4-3ce9-331c-97df-83397230b0df     36          Imagine

         sort-name country                     disambiguation  \
0  Imagine Dragons      US             American pop rock band
1       McKee, Ben      US  American bassist, Imagine Dragons
2     Beck, Andrew     NaN       early Imagine Dragons member
3          Imagine      US       US 70s progressive rock band
4          Imagine      CH        Swiss/Geneva hip-hop/rapper

                isnis                                            aliases  ...  \
0  [0000000468935478]  [{'sort-name': '이매진 드래곤스', 'type-id': '1937e40...  ...
1                 NaN  [{'sort-name': 'McKee, Benjamin Arthur', 'type...  ...
2                 NaN                                                NaN  ...
3                 NaN                                                NaN  ...
4                 NaN                                                NaN  ...

                     begin-area.type-id begin-area.name begin-area.sort-name  \
0  6fd8f29a-3d0a-32fc-980d-ea697b69da78       Las Vegas            Las Vegas
1  6fd8f29a-3d0a-32fc-980d-ea697b69da78     Forestville          Forestville
2                                   NaN             NaN                  NaN
3                                   NaN             NaN                  NaN
4                                   NaN             NaN                  NaN

  begin-area.life-span.ended life-span.begin life-span.ended  \
0                        NaN            2008            None
1                        NaN      1986-04-07            None
2                        NaN             NaN            None
3                        NaN             NaN            None
4                        NaN             NaN            None

                              gender-id gender           ipis life-span.end
0                                   NaN    NaN            NaN           NaN
1  36d3d30a-839d-3eda-8cb3-29be4384e4a9   male  [00595231632]           NaN
2  36d3d30a-839d-3eda-8cb3-29be4384e4a9   male            NaN           NaN
3                                   NaN    NaN            NaN           NaN
4  36d3d30a-839d-3eda-8cb3-29be4384e4a9   male            NaN           NaN

[5 rows x 29 columns]

In [46]:
df

,id,type,type-id,score,gender-id,name,sort-name,gender,country,area,begin-area,end-area,disambiguation,ipis,isnis,life-span,aliases,tags
0,f27ec8db-af05-4f36-916e-3d57f91ecf5e,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Michael Jackson,"Jackson, Michael",male,US,"{'id': '489ce91b-6658-3307-9877-795b68554c98',...","{'id': '34357067-8f7f-4c7a-8d5e-99b6e60f7891',...","{'id': '1f40c6e1-47ba-4e35-996f-fe6ee5840e62',...",“King of Pop”,"[00002961801, 00523553664]",[000000011023081X],"{'begin': '1958-08-29', 'end': '2009-06-25', '...","[{'sort-name': '迈克尔·杰克逊', 'name': '迈克尔·杰克逊', '...","[{'count': 1, 'name': 'rock'}, {'count': 20, '..."
1,8a92b6b3-1e91-45b5-8936-a0d6787a8be3,NaN,NaN,88,NaN,Michael Jackson,"Jackson, Michael",NaN,NaN,NaN,NaN,NaN,mashups,NaN,NaN,{'ended': None},NaN,NaN
2,f1be8703-f308-425a-ac31-6fb304cfb60c,Person,b6e035f4-3ce9-331c-97df-83397230b0df,88,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Michael Jackson,"Jackson, Michael",male,GB,"{'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed',...",NaN,NaN,vocals in English heavy metal band Pariah,NaN,NaN,{'ended': None},NaN,"[{'count': 1, 'name': 'invincible'}]"
3,ce8f1c65-1c0e-4685-bea5-f7a27a20b3bf,Person,b6e035f4-3ce9-331c-97df-83397230b0df,88,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Michael Jackson,"Jackson, Michael",male,AU,"{'id': '106e0bec-b638-3b37-b731-f53d507dc00e',...",NaN,NaN,Australian didgeridoo and didjeribone player,NaN,NaN,{'ended': None},NaN,NaN
4,e05cfe05-7e81-430e-a27b-fb910f46f008,NaN,NaN,88,NaN,Michael Jackson,"Jackson, Michael",NaN,NaN,NaN,NaN,NaN,Neal Morse related vocalist,NaN,NaN,{'ended': None},NaN,NaN
5,de05e891-e9ee-465c-ad70-6ace189b7cbb,Person,b6e035f4-3ce9-331c-97df-83397230b0df,88,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Michael Jackson,"Jackson, Michael",male,NZ,"{'id': '8524c7d9-f472-3890-a458-f28d5081d9c4',...","{'id': 'c6725380-3835-4f29-b795-3519258a00d4',...",NaN,NZ poet & anthropologist,NaN,[0000000110273174],"{'begin': '1939', 'ended': None}","[{'sort-name': 'Jackson, Michael D.', 'type-id...",NaN
6,5fc89998-cf26-4ec0-8fff-1398e34e7b61,Person,b6e035f4-3ce9-331c-97df-83397230b0df,76,36d3d30a-839d-3eda-8cb3-29be4384e4a9,George Michael Jackson,"Jackson, George Michael",male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'ended': None},NaN,NaN
7,49c562af-aa65-4a0b-998b-58d9b7df447e,NaN,NaN,76,NaN,Michael Jackson's Doctor,Michael Jackson's Doctor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'ended': None},NaN,NaN
8,c28f8611-9c71-4734-9f3c-2549fbd665bc,Person,b6e035f4-3ce9-331c-97df-83397230b0df,73,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Musa Keys,Musa Keys,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'ended': None},"[{'sort-name': 'Tsonga Michael Jackson', 'name...",NaN
9,5857471e-4238-4cd4-8c2e-1d9108db79c9,Person,b6e035f4-3ce9-331c-97df-83397230b0df,70,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Prince Michael Jackson I,"Jackson, Prince Michael, I",male,US,"{'id': '489ce91b-6658-3307-9877-795b68554c98',...","{'id': '1f40c6e1-47ba-4e35-996f-fe6ee5840e62',...",NaN,eldest son of Michael Jackson,NaN,NaN,"{'begin': '1997-02-13', 'ended': None}","[{'sort-name': 'Jackson, Michael Joseph, Jr.',...","[{'count': 1, 'name': 'soul'}]"
10,0af139d6-a56d-42c8-ab70-f27ceb9d5e92,Person,b6e035f4-3ce9-331c-97df-83397230b0df,62,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Christ'OF,Christ'OF,male,BE,"{'id': '5b8a5ee5-0bb3-34cf-9a75-c27c44e341fc',...",NaN,NaN,Belgian Michael Jackson impersonator,NaN,NaN,"{'begin': '1972-03-28', 'ended': None}","[{'sort-name': 'Lequesne, Christophe', 'type-i...",NaN
11,9d1818d3-0d61-4e76-b6c5-5b4883f792fd,Person,b6e035f4-3ce9-331c-97df-83397230b0df,61,93452b5a-a947-30c8-934f-6a4056b151c2,Paris Jackson,"Jackson, Paris",female,US,"{'id': '489ce91b-6658-3307-9877-795b68554c98',...","{'id': '73d8cbdd-3149-4cb6-a36d-1ef2036a8b88',...",NaN,daughter of Michael Jackson,NaN,NaN,"{'begin': '1998-04-03', 'ended': None}",NaN,NaN
12,9e697989-6e3e-46c3-ad0e-4bdf53f6b650,Person,b6e035f4-3ce9-331c-97df-83397230b0df,58,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Joe Jackson,"Jackson, Joe",male,US,"{'id': '489ce91b-6658-3307-9877-795b68554c98',...","{'id': '374ee737-5362-4e08-8a90-2ce32b3a764e',...","{'id': 'cd22d0ba-c79b-45b3-a8e0-617b240df5f0',...","manager, father of Michael Jackson",NaN,[0000000418227852],"{'begin': '1928-07-26', 'end': '2018-06-27', '...",NaN,NaN
13,78411cc5-b3e4-41fd-a5c2-96587f01a858,Person,b6e035f4-3ce9-331c-97df-83397230b0df,55,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Michael Starring Ben,Michael Starring Ben,male,GB,"{'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed',...",NaN,NaN,UK Michael Jackson tribute,NaN,NaN,{'ended': None},NaN,NaN
14,6faf0701-7b76-4695-9f8d-ccf8068f255d,Person,b6e035f4-3ce9-331c-97df-83397230b0df,54,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Juan Flowers,Juan Flowers,male,NaN,NaN,NaN,NaN,Michael Jackson tribute,NaN,NaN,{'ended': None},NaN,NaN
15,8aec52c2-d86f-4559-ae9e-2958bf341e11,NaN,NaN,50,NaN,Dangerous: All Metal Tribute to Michael Jackson,Dangerous: All Metal Tribute to Michael Jackson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'ended': None},NaN,NaN
16,059e57d8-af63-4d90-8078-ebed36985fff,Person,b6e035f4-3ce9-331c-97df-83397230b0df,48,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Mick Jackson,"Jackson, Mick",male,DE,"{'id': '85752fda-13c4-31a3-bee5-0e5cb1f51dad',...","{'id': '236912a5-dcd5-437b-9360-81d0d11d0540',...",NaN,"English singer-songwriter, “Blame It On the Bo...",[00017558966],[0000000080160987],"{'begin': '1947-11-02', 'ended': None}","[{'sort-name': 'Jackson-Clark, Michael George'...",NaN
17,27a2fbc6-4773-4b22-b90b-d594367851a9,Person,b6e035f4-3ce9-331c-97df-83397230b0df,44,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Mike Jackson,"Jackson, Mike",male,NaN,"{'id': '0eeb01c2-6e31-46ad-96b8-319749f731d2',...",NaN,NaN,"musician, aranger, writer",[00074908844],NaN,{'ended': None},"[{'sort-name': 'Jackson, Mike', 'name': 'Mike ...",NaN
18,df6e68aa-911d-4c8d-b823-5ccf8aea1db0,Person,b6e035f4-3ce9-331c-97df-83397230b0df,44,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Michael Gregory Jackson,"Jackson, Michael Gregory",male,US,"{'id': '489ce91b-6658-3307-9877-795b68554c98',...","{'id': '29754947-4414-4aa1-aeb1-b8bafb8b0e18',...",NaN,NaN,NaN,[0000000114010398],"{'begin': '1953-08-28', 'ended': None}","[{'sort-name': 'Gregory, Michael', 'type-id': ...","[{'count': 1, 'name': 'jazz'}]"
19,a60ed640-5c08-49a9-a25a-5937bb730b1c,Person,b6e035f4-3ce9-331c-97df-83397230b0df,44,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Mike Jackson,"Jackson, Mike",male,US,"{'id': '489ce91b-6658-3307-9877-795b68554c98',...","{'id': 'b21e4552-050d-4c0c-ac5a-031108eb0c47',...","{'id': '74e50e58-5deb-4b99-93a2-decbb365c07f',...","American jazz pianist and composer, 1888-1945",[00014971095],[0000000051350407],"{'begin': '1888-12-23', 'end': '1945-06-21', '...","[{'sort-name': 'Jackson, Michael C.', 'type-id...","[{'count': 1, 'name': 'jazz'}]"
20,c0437b64-4063-4f76-8082-1a865753b8e9,Person,b6e035f4-3ce9-331c-97df-83397230b0df,44,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Michael Lee Jackson,"Jackson, Michael Lee",male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'ended': None},NaN,NaN
21,a861b778-98fb-4748-9ffa-ff74c8f26f4f,Person,b6e035f4-3ce9-331c-97df-83397230b0df,44,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Michael Wayne Jackson,"Jackson, Michael Wayne",male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'ended': None},NaN,NaN
22,0f39b7d8-3924-46be-a373-e0229bafff52,Person,b6e035f4-3ce9-331c-97df-83397230b0df,43,NaN,マイケルジャクソン,"Jackson, Michael",NaN,NaN,NaN,NaN,NaN,vaporwave,NaN,NaN,{'ended': None},NaN,NaN
23,48ab3d35-5f10-429f-9709-7edc83c3cee5,Person,b6e035f4-3ce9-331c-97df-83397230b0df,43,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Michael C. Jackson,"Jackson, Michael C.",male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'ended': None},NaN,NaN
24,a6081db7-2123-4c8f-900f-c51cc36940e1,Person,b6e035f4-3ce9-331c-97df-83397230b0df,43,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Michael Thomas Jackson,"Jackson, Michael Thomas",male,NaN,NaN,NaN,NaN,clarinet,NaN,NaN,{'ended': None},NaN,NaN

In [22]:
df[df['type']=='Person']['name'].unique()

array(['Ben McKee', 'Andrew Beck', 'Imagine', 'King Imagine',
       'Imagine Mars', 'Imagine This'], dtype=object)

In [32]:
df.groupby([
    'type',
    'name']).agg({
    'id' : pd.Series.nunique,
    'type' : pd.Series.count
})

                         id  type
type   name
Group  Dragons            3     3
       Holy Dragons       1     1
       Imagine            2     2
       Imagine Dragons    1     1
       Imagine Music      1     1
       Imagine Sound      1     1
       Imagine That       1     1
       Jade Imagine       1     1
       Lucky Dragons      1     1
       The Soup Dragons   1     1
Person Andrew Beck        1     1
       Ben McKee          1     1
       Imagine            2     2
       Imagine Mars       1     1
       Imagine This       2     2
       King Imagine       1     1

In [33]:
df.shape

(25, 29)